version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.14.1
  parallelism: 1
  working_directory: ~/martinrey/hack-a-vote

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/martinrey
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run: yarn build
      - persist_to_workspace:
          root: ~/martinrey
          paths:
            - hack-a-vote
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/martinrey
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
